DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS responses;
DROP TABLE IF EXISTS attempts;
DROP TABLE IF EXISTS answer_options;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS rounds;
DROP TABLE IF EXISTS quizzes;
DROP TABLE IF EXISTS users;
