// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: payments/v1/payments.proto

package paymentspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentsService_CreatePayment_FullMethodName  = "/payments.v1.PaymentsService/CreatePayment"
	PaymentsService_SearchPayments_FullMethodName = "/payments.v1.PaymentsService/SearchPayments"
	PaymentsService_Refund_FullMethodName         = "/payments.v1.PaymentsService/Refund"
)

// PaymentsServiceClient is the client API for PaymentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentsService is the public API players talk to.
type PaymentsServiceClient interface {
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	SearchPayments(ctx context.Context, in *SearchPaymentsRequest, opts ...grpc.CallOption) (*SearchPaymentsResponse, error)
	Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error)
}

type paymentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentsServiceClient(cc grpc.ClientConnInterface) PaymentsServiceClient {
	return &paymentsServiceClient{cc}
}

func (c *paymentsServiceClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, PaymentsService_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) SearchPayments(ctx context.Context, in *SearchPaymentsRequest, opts ...grpc.CallOption) (*SearchPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPaymentsResponse)
	err := c.cc.Invoke(ctx, PaymentsService_SearchPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentsServiceClient) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*RefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundResponse)
	err := c.cc.Invoke(ctx, PaymentsService_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentsServiceServer is the server API for PaymentsService service.
// All implementations must embed UnimplementedPaymentsServiceServer
// for forward compatibility.
//
// PaymentsService is the public API players talk to.
type PaymentsServiceServer interface {
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	SearchPayments(context.Context, *SearchPaymentsRequest) (*SearchPaymentsResponse, error)
	Refund(context.Context, *RefundRequest) (*RefundResponse, error)
	mustEmbedUnimplementedPaymentsServiceServer()
}

// UnimplementedPaymentsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentsServiceServer struct{}

func (UnimplementedPaymentsServiceServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentsServiceServer) SearchPayments(context.Context, *SearchPaymentsRequest) (*SearchPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchPayments not implemented")
}
func (UnimplementedPaymentsServiceServer) Refund(context.Context, *RefundRequest) (*RefundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedPaymentsServiceServer) mustEmbedUnimplementedPaymentsServiceServer() {}
func (UnimplementedPaymentsServiceServer) testEmbeddedByValue()                         {}

// UnsafePaymentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentsServiceServer will
// result in compilation errors.
type UnsafePaymentsServiceServer interface {
	mustEmbedUnimplementedPaymentsServiceServer()
}

func RegisterPaymentsServiceServer(s grpc.ServiceRegistrar, srv PaymentsServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentsService_ServiceDesc, srv)
}

func _PaymentsService_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_SearchPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).SearchPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_SearchPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).SearchPayments(ctx, req.(*SearchPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentsService_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentsServiceServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentsService_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentsServiceServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentsService_ServiceDesc is the grpc.ServiceDesc for PaymentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.v1.PaymentsService",
	HandlerType: (*PaymentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePayment",
			Handler:    _PaymentsService_CreatePayment_Handler,
		},
		{
			MethodName: "SearchPayments",
			Handler:    _PaymentsService_SearchPayments_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _PaymentsService_Refund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments/v1/payments.proto",
}

const (
	AdminPaymentsService_PaymentHistory_FullMethodName = "/payments.v1.AdminPaymentsService/PaymentHistory"
	AdminPaymentsService_ExportPayments_FullMethodName = "/payments.v1.AdminPaymentsService/ExportPayments"
)

// AdminPaymentsServiceClient is the client API for AdminPaymentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminPaymentsService is the internal API, served on a separate port.
type AdminPaymentsServiceClient interface {
	PaymentHistory(ctx context.Context, in *PaymentHistoryRequest, opts ...grpc.CallOption) (*SearchPaymentsResponse, error)
	ExportPayments(ctx context.Context, in *ExportPaymentsRequest, opts ...grpc.CallOption) (*ExportPaymentsResponse, error)
}

type adminPaymentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminPaymentsServiceClient(cc grpc.ClientConnInterface) AdminPaymentsServiceClient {
	return &adminPaymentsServiceClient{cc}
}

func (c *adminPaymentsServiceClient) PaymentHistory(ctx context.Context, in *PaymentHistoryRequest, opts ...grpc.CallOption) (*SearchPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPaymentsResponse)
	err := c.cc.Invoke(ctx, AdminPaymentsService_PaymentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminPaymentsServiceClient) ExportPayments(ctx context.Context, in *ExportPaymentsRequest, opts ...grpc.CallOption) (*ExportPaymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportPaymentsResponse)
	err := c.cc.Invoke(ctx, AdminPaymentsService_ExportPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminPaymentsServiceServer is the server API for AdminPaymentsService service.
// All implementations must embed UnimplementedAdminPaymentsServiceServer
// for forward compatibility.
//
// AdminPaymentsService is the internal API, served on a separate port.
type AdminPaymentsServiceServer interface {
	PaymentHistory(context.Context, *PaymentHistoryRequest) (*SearchPaymentsResponse, error)
	ExportPayments(context.Context, *ExportPaymentsRequest) (*ExportPaymentsResponse, error)
	mustEmbedUnimplementedAdminPaymentsServiceServer()
}

// UnimplementedAdminPaymentsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminPaymentsServiceServer struct{}

func (UnimplementedAdminPaymentsServiceServer) PaymentHistory(context.Context, *PaymentHistoryRequest) (*SearchPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PaymentHistory not implemented")
}
func (UnimplementedAdminPaymentsServiceServer) ExportPayments(context.Context, *ExportPaymentsRequest) (*ExportPaymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportPayments not implemented")
}
func (UnimplementedAdminPaymentsServiceServer) mustEmbedUnimplementedAdminPaymentsServiceServer() {}
func (UnimplementedAdminPaymentsServiceServer) testEmbeddedByValue()                              {}

// UnsafeAdminPaymentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminPaymentsServiceServer will
// result in compilation errors.
type UnsafeAdminPaymentsServiceServer interface {
	mustEmbedUnimplementedAdminPaymentsServiceServer()
}

func RegisterAdminPaymentsServiceServer(s grpc.ServiceRegistrar, srv AdminPaymentsServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminPaymentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminPaymentsService_ServiceDesc, srv)
}

func _AdminPaymentsService_PaymentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPaymentsServiceServer).PaymentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPaymentsService_PaymentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPaymentsServiceServer).PaymentHistory(ctx, req.(*PaymentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminPaymentsService_ExportPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPaymentsServiceServer).ExportPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPaymentsService_ExportPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPaymentsServiceServer).ExportPayments(ctx, req.(*ExportPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminPaymentsService_ServiceDesc is the grpc.ServiceDesc for AdminPaymentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminPaymentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payments.v1.AdminPaymentsService",
	HandlerType: (*AdminPaymentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PaymentHistory",
			Handler:    _AdminPaymentsService_PaymentHistory_Handler,
		},
		{
			MethodName: "ExportPayments",
			Handler:    _AdminPaymentsService_ExportPayments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments/v1/payments.proto",
}
