// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payments/v1/payments.proto

package paymentspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pan           string                 `protobuf:"bytes,1,opt,name=pan,proto3" json:"pan,omitempty"`
	Cvv           string                 `protobuf:"bytes,2,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Holder        string                 `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	ExpiryMonth   int32                  `protobuf:"varint,4,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear    int32                  `protobuf:"varint,5,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_payments_v1_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetPan() string {
	if x != nil {
		return x.Pan
	}
	return ""
}

func (x *Card) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *Card) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *Card) GetExpiryMonth() int32 {
	if x != nil {
		return x.ExpiryMonth
	}
	return 0
}

func (x *Card) GetExpiryYear() int32 {
	if x != nil {
		return x.ExpiryYear
	}
	return 0
}

type Payer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	TaxId         string                 `protobuf:"bytes,4,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payer) Reset() {
	*x = Payer{}
	mi := &file_payments_v1_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payer) ProtoMessage() {}

func (x *Payer) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payer.ProtoReflect.Descriptor instead.
func (*Payer) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{1}
}

func (x *Payer) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Payer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Payer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Payer) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId        int64                  `protobuf:"varint,2,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Card          *Card                  `protobuf:"bytes,5,opt,name=card,proto3" json:"card,omitempty"`
	Payer         *Payer                 `protobuf:"bytes,6,opt,name=payer,proto3" json:"payer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payments_v1_payments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentRequest) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *CreatePaymentRequest) GetPayer() *Payer {
	if x != nil {
		return x.Payer
	}
	return nil
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuizId        int64                  `protobuf:"varint,3,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	CardLast4     string                 `protobuf:"bytes,6,opt,name=card_last4,json=cardLast4,proto3" json:"card_last4,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payments_v1_payments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{3}
}

func (x *Payment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Payment) GetQuizId() int64 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetCardLast4() string {
	if x != nil {
		return x.CardLast4
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_payments_v1_payments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type SearchPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	OrderBy       string                 `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPaymentsRequest) Reset() {
	*x = SearchPaymentsRequest{}
	mi := &file_payments_v1_payments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPaymentsRequest) ProtoMessage() {}

func (x *SearchPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPaymentsRequest.ProtoReflect.Descriptor instead.
func (*SearchPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{5}
}

func (x *SearchPaymentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchPaymentsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type SearchPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPaymentsResponse) Reset() {
	*x = SearchPaymentsResponse{}
	mi := &file_payments_v1_payments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPaymentsResponse) ProtoMessage() {}

func (x *SearchPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPaymentsResponse.ProtoReflect.Descriptor instead.
func (*SearchPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{6}
}

func (x *SearchPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Card          *Card                  `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_payments_v1_payments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{7}
}

func (x *RefundRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *RefundRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *RefundRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_payments_v1_payments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{8}
}

func (x *RefundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PaymentHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentHistoryRequest) Reset() {
	*x = PaymentHistoryRequest{}
	mi := &file_payments_v1_payments_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentHistoryRequest) ProtoMessage() {}

func (x *PaymentHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentHistoryRequest.ProtoReflect.Descriptor instead.
func (*PaymentHistoryRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentHistoryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ExportPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPaymentsRequest) Reset() {
	*x = ExportPaymentsRequest{}
	mi := &file_payments_v1_payments_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPaymentsRequest) ProtoMessage() {}

func (x *ExportPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ExportPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{10}
}

func (x *ExportPaymentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExportPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Csv           []byte                 `protobuf:"bytes,1,opt,name=csv,proto3" json:"csv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportPaymentsResponse) Reset() {
	*x = ExportPaymentsResponse{}
	mi := &file_payments_v1_payments_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportPaymentsResponse) ProtoMessage() {}

func (x *ExportPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payments_v1_payments_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ExportPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payments_v1_payments_proto_rawDescGZIP(), []int{11}
}

func (x *ExportPaymentsResponse) GetCsv() []byte {
	if x != nil {
		return x.Csv
	}
	return nil
}

var File_payments_v1_payments_proto protoreflect.FileDescriptor

const file_payments_v1_payments_proto_rawDesc = "" +
	"\n" +
	"\x1apayments/v1/payments.proto\x12\vpayments.v1\"\x86\x01\n" +
	"\x04Card\x12\x10\n" +
	"\x03pan\x18\x01 \x01(\tR\x03pan\x12\x10\n" +
	"\x03cvv\x18\x02 \x01(\tR\x03cvv\x12\x16\n" +
	"\x06holder\x18\x03 \x01(\tR\x06holder\x12!\n" +
	"\fexpiry_month\x18\x04 \x01(\x05R\vexpiryMonth\x12\x1f\n" +
	"\vexpiry_year\x18\x05 \x01(\x05R\n" +
	"expiryYear\"g\n" +
	"\x05Payer\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x15\n" +
	"\x06tax_id\x18\x04 \x01(\tR\x05taxId\"\xcd\x01\n" +
	"\x14CreatePaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\aquiz_id\x18\x02 \x01(\x03R\x06quizId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x04card\x18\x05 \x01(\v2\x11.payments.v1.CardR\x04card\x12(\n" +
	"\x05payer\x18\x06 \x01(\v2\x12.payments.v1.PayerR\x05payer\"\xb6\x01\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\aquiz_id\x18\x03 \x01(\x03R\x06quizId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"card_last4\x18\x06 \x01(\tR\tcardLast4\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"G\n" +
	"\x15CreatePaymentResponse\x12.\n" +
	"\apayment\x18\x01 \x01(\v2\x14.payments.v1.PaymentR\apayment\"J\n" +
	"\x15SearchPaymentsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\border_by\x18\x02 \x01(\tR\aorderBy\"J\n" +
	"\x16SearchPaymentsResponse\x120\n" +
	"\bpayments\x18\x01 \x03(\v2\x14.payments.v1.PaymentR\bpayments\"m\n" +
	"\rRefundRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12%\n" +
	"\x04card\x18\x02 \x01(\v2\x11.payments.v1.CardR\x04card\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"(\n" +
	"\x0eRefundResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"0\n" +
	"\x15PaymentHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"/\n" +
	"\x15ExportPaymentsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"*\n" +
	"\x16ExportPaymentsResponse\x12\x10\n" +
	"\x03csv\x18\x01 \x01(\fR\x03csv2\x87\x02\n" +
	"\x0fPaymentsService\x12V\n" +
	"\rCreatePayment\x12!.payments.v1.CreatePaymentRequest\x1a\".payments.v1.CreatePaymentResponse\x12Y\n" +
	"\x0eSearchPayments\x12\".payments.v1.SearchPaymentsRequest\x1a#.payments.v1.SearchPaymentsResponse\x12A\n" +
	"\x06Refund\x12\x1a.payments.v1.RefundRequest\x1a\x1b.payments.v1.RefundResponse2\xcc\x01\n" +
	"\x14AdminPaymentsService\x12Y\n" +
	"\x0ePaymentHistory\x12\".payments.v1.PaymentHistoryRequest\x1a#.payments.v1.SearchPaymentsResponse\x12Y\n" +
	"\x0eExportPayments\x12\".payments.v1.ExportPaymentsRequest\x1a#.payments.v1.ExportPaymentsResponseB@Z>github.com/spndxyz/quiz/internal/grpcapi/paymentspb;paymentspbb\x06proto3"

var (
	file_payments_v1_payments_proto_rawDescOnce sync.Once
	file_payments_v1_payments_proto_rawDescData []byte
)

func file_payments_v1_payments_proto_rawDescGZIP() []byte {
	file_payments_v1_payments_proto_rawDescOnce.Do(func() {
		file_payments_v1_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payments_v1_payments_proto_rawDesc), len(file_payments_v1_payments_proto_rawDesc)))
	})
	return file_payments_v1_payments_proto_rawDescData
}

var file_payments_v1_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_payments_v1_payments_proto_goTypes = []any{
	(*Card)(nil),                   // 0: payments.v1.Card
	(*Payer)(nil),                  // 1: payments.v1.Payer
	(*CreatePaymentRequest)(nil),   // 2: payments.v1.CreatePaymentRequest
	(*Payment)(nil),                // 3: payments.v1.Payment
	(*CreatePaymentResponse)(nil),  // 4: payments.v1.CreatePaymentResponse
	(*SearchPaymentsRequest)(nil),  // 5: payments.v1.SearchPaymentsRequest
	(*SearchPaymentsResponse)(nil), // 6: payments.v1.SearchPaymentsResponse
	(*RefundRequest)(nil),          // 7: payments.v1.RefundRequest
	(*RefundResponse)(nil),         // 8: payments.v1.RefundResponse
	(*PaymentHistoryRequest)(nil),  // 9: payments.v1.PaymentHistoryRequest
	(*ExportPaymentsRequest)(nil),  // 10: payments.v1.ExportPaymentsRequest
	(*ExportPaymentsResponse)(nil), // 11: payments.v1.ExportPaymentsResponse
}
var file_payments_v1_payments_proto_depIdxs = []int32{
	0,  // 0: payments.v1.CreatePaymentRequest.card:type_name -> payments.v1.Card
	1,  // 1: payments.v1.CreatePaymentRequest.payer:type_name -> payments.v1.Payer
	3,  // 2: payments.v1.CreatePaymentResponse.payment:type_name -> payments.v1.Payment
	3,  // 3: payments.v1.SearchPaymentsResponse.payments:type_name -> payments.v1.Payment
	0,  // 4: payments.v1.RefundRequest.card:type_name -> payments.v1.Card
	2,  // 5: payments.v1.PaymentsService.CreatePayment:input_type -> payments.v1.CreatePaymentRequest
	5,  // 6: payments.v1.PaymentsService.SearchPayments:input_type -> payments.v1.SearchPaymentsRequest
	7,  // 7: payments.v1.PaymentsService.Refund:input_type -> payments.v1.RefundRequest
	9,  // 8: payments.v1.AdminPaymentsService.PaymentHistory:input_type -> payments.v1.PaymentHistoryRequest
	10, // 9: payments.v1.AdminPaymentsService.ExportPayments:input_type -> payments.v1.ExportPaymentsRequest
	4,  // 10: payments.v1.PaymentsService.CreatePayment:output_type -> payments.v1.CreatePaymentResponse
	6,  // 11: payments.v1.PaymentsService.SearchPayments:output_type -> payments.v1.SearchPaymentsResponse
	8,  // 12: payments.v1.PaymentsService.Refund:output_type -> payments.v1.RefundResponse
	6,  // 13: payments.v1.AdminPaymentsService.PaymentHistory:output_type -> payments.v1.SearchPaymentsResponse
	11, // 14: payments.v1.AdminPaymentsService.ExportPayments:output_type -> payments.v1.ExportPaymentsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_payments_v1_payments_proto_init() }
func file_payments_v1_payments_proto_init() {
	if File_payments_v1_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payments_v1_payments_proto_rawDesc), len(file_payments_v1_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_payments_v1_payments_proto_goTypes,
		DependencyIndexes: file_payments_v1_payments_proto_depIdxs,
		MessageInfos:      file_payments_v1_payments_proto_msgTypes,
	}.Build()
	File_payments_v1_payments_proto = out.File
	file_payments_v1_payments_proto_goTypes = nil
	file_payments_v1_payments_proto_depIdxs = nil
}
